### ISSUE TITLE
License query

### ISSUE THREAD

**Issue by jbduncan** [Erdos-Graph-Framework/Erdos#1]
Hi Erdos-Graph-Framework team.

I've noticed that the README says that Erdos is considered to be `production proved code. Used in a commercial project.`

However, I've also noticed that Erdos is GPL-2.0 licensed. Is the commercial project mentioned in the README licensed under the GPL-2.0 as well?

**Comment by HendrixString** [comment]
hi @jbduncan , it didn't have too since it didn't fork the source code. if you fork and modify things, then I think the license means that you have to share the fork. It doesn't mean that you  have to share your application, only the forked library. would you rather have a different license ?

**Comment by jbduncan** [comment]
Hi @HendrixString.

IANAL, but by my admittedly limited understanding, if _anything_ links to a GPL-2.0 library (whether it's another library, an application, or anything else), then it _must_ also be licensed under the GPL-2.0 as well, which means that it must make its source code publicly available somewhere.

This is not a huge dealbreaker for me personally, but I am concerned for your sake (and/or the sake of the people who own this commercial project) that you/they are breaking the law if the source code for this commercial project _isn't_ available right now.

So, if I had a say in this, then yes, I would rather that Erdos is licensed under a more permissive license. :)

**Comment by HendrixString** [comment]
can be done, Apache v2 would be more permissive

**Comment by jbduncan** [comment]
Cool! I personally have no objections with Apache 2.0, so I'd be happy to see Erdos switch to that particular license. :+1:

I'm more than happy to close this issue once the license has been changed.

**Comment by HendrixString** [comment]
@jbduncan changed the license to MIT which is very permissive (and even less strict then Apache 2) ;)

**Comment by jbduncan** [comment]
Great! Closing this issue as fixed then. :)
