### ISSUE TITLE
FrequencyIterator doesn't decrease the frequency of current

### ISSUE THREAD

**Issue by adam-arold** [Erdos-Graph-Framework/Erdos#4]
By looking at the implementation I can see that `current` is never assigned, and when `remove` is called on the `Iterator` `null` is passed to `decreaseFrequencyOf`.

**Comment by HendrixString** [comment]
@adam-arold 
Hey Adam, I ended up not using this class and can't remember why.
I never tested the iterator and you are correct, `current` is never updated
and it should.

you are most welcome to propose a patch.

also, I guess you were looking for iterators examples, you can find examples
in the graph classes

**Comment by adam-arold** [comment]
I'm doing a port of Erdos to Kotlin right now and I noticed this problem. If it turns out that the class is unused I'll just delete it. :)

**Comment by HendrixString** [comment]
@adam-arold 
it would be great if you could commit your kotlin work
as a new repository of `Erdos-Graph-Framework` organization
and of course become a member with write access etc..

**Comment by adam-arold** [comment]
I can add it as a remote if you want. I'm going to mention in the docs that it is a port of Erdos.

**Comment by HendrixString** [comment]
cool
